# Generated by Django 4.0 on 2021-12-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Now',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Current_TotalBallance_In_Wallet', models.IntegerField()),
                ('CryptoName', models.CharField(max_length=40)),
                ('Buying_Price', models.FloatField()),
                ('Ammount', models.FloatField()),
                ('TimeAndDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
